### ISSUE TITLE
Need better readme for installation

### ISSUE THREAD

**Issue by rsoorajs** [azizbekx/Yandex_translate_Bot#1]
where should i add `Telegram bot token` ?

**Comment by azizbekx** [comment]
Well done! Update readme file  
Thanks for you interest in my project

**Comment by rsoorajs** [comment]
![IMG_20201123_153702_517](https://user-images.githubusercontent.com/20116017/99950510-a0c2b980-2da2-11eb-82d8-2389f90345c8.jpg)


what is this error ? i am trying to deploy in docker..
